server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userservice1?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mapping: true
        show-sql: false
        format_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}

jwt:
  signerKey: ${TOKEN}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator endpoints exposure
management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


      